name: "Releases"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  main:
    permissions:
      id-token: write
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          export DETECT_CHROMEDRIVER_VERSION=true
          npm ci
          npm run setheapsize

      - name: Lint
        run: npx grunt lint

      - name: Unit Tests
        run: |
          npm test
          npm run testnodeconsumer

      - name: Production Build
        run: npx grunt prod

      - name: UI Tests
        run: |
          sudo apt-get install xvfb
          xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Image Metadata
        id: image-metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Upload Release Assets
        id: upload-release-assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/prod/*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "详情请参考[SRK Toolbox CHANGELOG](https://github.com/Raka-loah/SRK-Toolbox/blob/master/CHANGELOG_SRKTOOLBOX.md)和CyberChef原版[CHANGELOG](https://github.com/gchq/CyberChef/blob/master/CHANGELOG.md)以及[commit messages](https://github.com/gchq/CyberChef/commits/master)。"

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: rakaloah/srk-toolbox

      - name: Docker Login
        if: success()
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Setup Buildx
        if: success()
        uses: docker/setup-buildx-action@v2.2.1
        
      - name: Build and push Docker images
        if: success()
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
